### ISSUE TITLE
LoadNewLensSeq() returns a ZemaxUI.ZOSAPI.ZemaxSystem instead of  zospy.zpcore.OpticStudioSystem

### ISSUE THREAD

**Issue by Omnistic** [MREYE-LUMC/ZOSPy#52]
### Problem

As a result of searching with the LensCatalog tool, it is possible to retrieve an ILensCatalogLens. Then, one can retrieve an IOpticalSystem from the method LoadNewLensSeq() or LoadNewLensNonSeq(). Currently this IOpticalSystem is a ZemaxUI.ZOSAPI.ZemaxSystem, which is the default type from the ZOSAPI. In comparison, the primary OpticalSystem in ZOSPy is a zospy.zpcore.OpticStudioSystem object. I think it would be more consistant if the return of LoadNewLensSeq() would also be a zospy.zpcore.OpticStudioSystem object. I hope this makes sense, and thank you for your great work.

### What version of ZOSPy are you running?

1.1.1

### What version of OpticStudio are you running?

R2.00

### Which operating system do you use?

Windows 10 Pro

### In which environment do you use ZOSPy?

- [X] Plain Pythons scripts (not in Spyder)
- [X] Jupyter notebooks
- [ ] Spyder

### In which connection modes does the problem occur?

- [X] Extension mode
- [X] Standalone mode

### Example code

```Python
import zospy as zp

zos = zp.ZOS()
zos.wakeup()
zos.connect_as_extension()
oss = zos.get_primary_system()

lensCatalog = oss.Tools.OpenLensCatalogs()
lensCatalog.RunAndWaitForCompletion()
dummySystem = lensCatalog.GetResult(0).LoadNewLensSeq()
lensCatalog.Close()

print(oss)
print(dummySystem)
```

### Output

```Python
<zospy.zpcore.OpticStudioSystem object at 0x000002229CF74990>
ZemaxUI.ZOSAPI.ZemaxSystem






​
```

**Comment by crnh** [comment]
Hi @Omnistic,

Thanks for reporting this issue! I just looked into the OpticStudio documentation and `lensCatalog.GetResult(0).LoadNewLensSeq()` indeed returns an object implementing the `IOpticalSystem` interface.
Since this optical system is created through directly calling the ZOS-API, it is not wrapped in an `OpticStudioSystem` class. This is by design, as we do not intercept any calls made to the ZOS-API. You need to convert it to an `OpticStudioSystem` object yourself:

```python
dummySystem = zp.OpticStudioSystem(zos, lensCatalog.GetResult(0).LoadNewLensSeq())
```

That being said, we are working on a method that allows us to "intercept" calls to the ZOS-API and automatically perform conversions to ZOSPy's own types. This functionality is planned for the next release. We will discuss if we can use this method to automatically perform this conversion as well (although I am not sure if this is possible, because `OpticStudioSystem._System` still needs to be of the `ZemaxUI.ZOSAPI.ZemaxSystem` type, and that object would then be converted as well).

**Comment by Omnistic** [comment]
Hi @crnh,


Thank you for this information. I suspected this was not a bug, but since I spent quite some time figuring out what was happening in my code I thought it would be good to have a reference about this somewhere.

Take care,


David

**Comment by Omnistic** [comment]
Actually @crnh, when I make the modification to the code:

```
import zospy as zp

zos = zp.ZOS()
zos.wakeup()
zos.connect_as_extension()
oss = zos.get_primary_system()

lensCatalog = oss.Tools.OpenLensCatalogs()
lensCatalog.RunAndWaitForCompletion()
dummySystem = zp.OpticStudioSystem(zos, lensCatalog.GetResult(0).LoadNewLensSeq())
lensCatalog.Close()
```

I get

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 10
      8 lensCatalog = oss.Tools.OpenLensCatalogs()
      9 lensCatalog.RunAndWaitForCompletion()
---> 10 dummySystem = zp.OpticStudioSystem(zos, lensCatalog.GetResult(0).LoadNewLensSeq())
     11 lensCatalog.Close()

AttributeError: module 'zospy' has no attribute 'OpticStudioSystem'
```

Do you know what I could be doing wrong?

Thanks for your help and take care,


David
